### ISSUE TITLE
Thank you, but the active area is much smaller than the real one

### ISSUE THREAD

**Issue by link1988114** [sherluok/esp370u#1]
it works well, but the area in the page is about 3/4 of the real one, is there anyway to modify it?

**Comment by sherluok** [comment]
You can rewrite the style of canvas element passed to `emulate()` function.
[Modify this](https://github.com/sherluok/esp370u/blob/7371b220f3ab2559b2f5b0c5fa9614205d0d4abe/docs/index.html#L34)

**Comment by link1988114** [comment]
Thanks!  It works!
